const { compose } = require('./compose.js');

// I'm not writing all of these out - scripting is better, if less performant. oof.
const _elements = [
    "address",
    "article",
    "aside",
    "footer",
    "header",
    "h1", "h2", "h3", "h4", "h5",
    "hgroup",
    "main",
    "nav",
    "section",
    "blockquote",
    "div",
    "hr",
    "li",
    "main",
    "ol",
    "p",
    "pre",
    "ul",
    "a",
    "br",
    "code",
    "em",
    "i",
    "small",
    "span",
    "strong",
    "sub",
    "sup",
    "time",
    "area",
    "audio",
    "img",
    "map",
    "track",
    "video",
    "embed",
    "iframe",
    "noembed",
    "object",
    "picture",
    "source",
    "canvas",
    "caption",
    "col",
    "colgroup",
    "table",
    "tbody",
    "td",
    "tfoot",
    "th",
    "thead",
    "tr",
    "button",
    "datalist",
    "fieldset",
    "form",
    "input",
    "label",
    "legend",
    "meter",
    "optgroup",
    "option",
    "select",
    "textarea",
    "details",
    "summary"
];

const element = exports.element = function(tag) {
    return compose((inner) => `<${tag}>${inner}</${tag}>`);
};

_elements.forEach((tag) => {
    exports[tag] = element(tag);
});
